name: Code Quality

on:
  schedule:
    - cron: '33 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches: '*'

  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Check formatting
      run: bun format

    - name: Run linter
      run: bun lint
