name: TS Build

on:
  schedule:
    - cron: "30 01 * * *"
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install packages
        if: always()
        run: bun install

      - name: Install expo
        if: always()
        run: bunx expo install --check

      - name: Build packages
        if: always()
        run: bunx expo-doctor

      - name: do deps need updates
        if: always()
        run: bun update

      - name: what updates are available
        if: always()
        run: bun outdated
