name: dependencies

on:
  schedule:
    - cron: "30 01 * * *"
  push:
    branches: ['*']
  pull_request:
    types: [opened, synchronize]

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Install packages
        if: always()
        run: npm install

      - name: Install expo
        if: always()
        run: npx expo install --check

      - name: Build packages
        if: always()
        run: npx expo-doctor

      - name: do deps need updates
        if: always()
        run: npm update

      - name: what updates are available
        if: always()
        run: npx npm-check-updates
