name: Expo Prebuild Android

on:
  schedule:
    - cron: "31 10 * * *"
  push:
    branches: ['*']
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  prebuild-android:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v4

    - name: Install packages
      run: npm install

    - name: prebuild android
      run: npx expo prebuild -p android --clean
